# Generated by Django 3.2.8 on 2024-04-10 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('uid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=16)),
                ('img_url', models.CharField(default='', max_length=100)),
                ('level', models.CharField(default='0', max_length=4)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='userBans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_time', models.DateTimeField()),
                ('operatorUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userBans_ban', to='streamingPlatform.users')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userBans_baned', to='streamingPlatform.users')),
            ],
        ),
        migrations.CreateModel(
            name='StreamCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streamingPlatform.users')),
            ],
        ),
        migrations.CreateModel(
            name='roomBans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_time', models.DateTimeField()),
                ('operatorUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roomBans_ban', to='streamingPlatform.users')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roomBans_baned', to='streamingPlatform.users')),
            ],
        ),
        migrations.CreateModel(
            name='Fans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fans_fan', to='streamingPlatform.users')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fans_follower', to='streamingPlatform.users')),
            ],
            options={
                'unique_together': {('follower', 'fan')},
            },
        ),
    ]
