# Generated by Django 3.2.8 on 2024-04-10 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamingPlatform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamcode',
            name='content',
            field=models.CharField(default='欢迎来到我的直播间~', max_length=100),
        ),
    ]
