# Generated by Django 3.2.8 on 2024-05-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamingPlatform', '0002_streamcode_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamcode',
            name='is_open',
            field=models.CharField(default='0', max_length=2),
        ),
    ]
