# Generated by Django 3.2.8 on 2024-05-15 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streamingPlatform', '0003_streamcode_is_open'),
    ]

    operations = [
        migrations.CreateModel(
            name='liveCounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(auto_now_add=True)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streamingPlatform.users')),
            ],
        ),
    ]
