# Generated by Django 3.2.8 on 2024-05-15 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streamingPlatform', '0004_livecounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='userContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_time', models.DateTimeField()),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to='streamingPlatform.users')),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2', to='streamingPlatform.users')),
            ],
        ),
    ]
