# Generated by Django 3.2.8 on 2024-05-16 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamingPlatform', '0005_usercontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livecounts',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='livecounts',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
